"""Optional local HTTP service for :mod:`pii_zh.cascade`."""

from .app import (
    DEFAULT_CUDA_MAX_CONCURRENCY,
    DEFAULT_HOST,
    DEFAULT_MAX_CONCURRENCY,
    DEFAULT_MAX_REQUEST_BODY_BYTES,
    DEFAULT_MAX_TEXT_CHARS,
    DEFAULT_PORT,
    DEFAULT_REQUEST_TIMEOUT_SECONDS,
    SERVICE_OUTPUT_SCHEMA_VERSION,
    create_app,
    run,
)

__all__ = [
    "DEFAULT_CUDA_MAX_CONCURRENCY",
    "DEFAULT_HOST",
    "DEFAULT_MAX_CONCURRENCY",
    "DEFAULT_MAX_REQUEST_BODY_BYTES",
    "DEFAULT_MAX_TEXT_CHARS",
    "DEFAULT_PORT",
    "DEFAULT_REQUEST_TIMEOUT_SECONDS",
    "SERVICE_OUTPUT_SCHEMA_VERSION",
    "create_app",
    "run",
]
